version: '3.8'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
    users:
        container_name: user-service
        build:
            context: .
            dockerfile: ./backend/user-service/Dockerfile
        ports:
            - "3001:3001"
        env_file:
            - ./backend/user-service/.env

    questions:
        container_name: question-service
        build:
            context: .
            dockerfile: ./mongodb-database/Dockerfile
        ports:
            - "3002:3002"
        env_file:
            - ./mongodb-database/.env

    matching:
        container_name: matching-service
        build:
            context: .
            dockerfile: ./matching-service/Dockerfile
        ports:
            - "3004:3004"
        env_file:
            - ./matching-service/.env

    collaboration:
        container_name: collaboration-service
        build:
            context: .
            dockerfile: ./collaboration-service/Dockerfile
        ports:
            - "3005:3005"

    server:
        image: judge0/judge0:1.13.0
        volumes:
            - ./backend/judge0/judge0.conf:/judge0.conf:ro
        ports:
            - "2358:2358"
        privileged: true
        <<: *default-logging
        restart: always

    workers:
        image: judge0/judge0:1.13.0
        command: ["./scripts/workers"]
        volumes:
            - ./backend/judge0/judge0.conf:/judge0.conf:ro
        privileged: true
        <<: *default-logging
        restart: always

    db:
        image: postgres:13.0
        env_file: ./backend/judge0/judge0.conf
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        <<: *default-logging
        restart: always

    redis:
        image: redis:6.0
        command: [
            "bash", "-c",
            'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
        ]
        env_file: ./backend/judge0/judge0.conf
        volumes:
            - redis-data:/data
        <<: *default-logging
        restart: always

    rabbitmq:
        image: rabbitmq:management
        hostname: rabbitmq
        ports:
            - "5672:5672"      # AMQP protocol
            - "15672:15672"    # Management UI
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_log:/var/log/rabbitmq

volumes:
    postgres-data:
    redis-data:
    rabbitmq_data:
    rabbitmq_log:
    