version: '3.8'

services:
    users:
        container_name: user-service
        build:
            context: .
            dockerfile: ./backend/user-service/Dockerfile
        ports:
            - "3001:3001"
        env_file:
            - ./backend/user-service/.env

    questions:
        container_name: question-service
        build:
            context: .
            dockerfile: ./mongodb-database/Dockerfile
        ports:
            - "3002:3002"
        env_file:
            - ./mongodb-database/.env
    
    matching:
        container_name: matching-service
        build:
            context: .
            dockerfile: ./matching-service/Dockerfile
        ports:
            - "3004:3004"
        env_file:
            - ./matching-service/.env

    collaboration:
        container_name: collaboration-service
        build:
            context: .
            dockerfile: ./collaboration-service/Dockerfile
        ports:
            - "3005:3005"
