http:
    port: 8080
admin:
    port: 9876
    host: localhost
apiEndpoints:
    # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
    user:
        host: "*"
        paths:
            - "/api/users"
            - "/api/login"
            - "/api/logout"
            - "/api/token-login"
    questionBank:
        host: "*"
        paths:
            - "/add-new-question"
            - "/get-all-questions"
            - "/delete-question"
            - "/edit-question"
    matching:
        host: "*"
        paths:
            - "/start-match"
    collaboration:
        host: "*"
        paths:
            - "/start-collab"

serviceEndpoints:
    # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
    userService:
        url: "http://localhost:3001"
    questionService:
        url: "http://localhost:3002"
    matchingService:
        url: "http://localhost:3004"
    collabService:
        url: "http://localhost:3005"

policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit

pipelines:
    # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
    userPipeline:
        apiEndpoints:
            - user
        policies:
            - proxy:
                  - action:
                        serviceEndpoint: userService
    questionPipeline:
        apiEndpoints:
            - questionBank
        policies:
            - proxy:
                  - action:
                        serviceEndpoint: questionService
    matchingPipeline:
        apiEndpoints:
            - matching
        policies:
            - proxy:
                  - action:
                        serviceEndpoint: matchingService
    collaborationPipeline:
        apiEndpoints:
            - collaboration
        policies:
            - proxy:
                  - action:
                        serviceEndpoint: collaborationService
