http:
    port: 8080
admin:
    port: 9876
    host: localhost
apiEndpoints:
    # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
    user:
        host: "*"
        paths:
            - "/api/users"
            - "/api/users/verify-invitation"
            - "/api/login"
            - "/api/logout"
            - "/api/token-login"
            - "/api/invite"
    questionBank:
        host: "*"
        paths:
            - "/add-new-question"
            - "/get-all-questions"
            - "/delete-question"
            - "/edit-question"

serviceEndpoints:
    # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
    userService:
        url: "http://localhost:3001"
    questionService:
        url: "http://localhost:3002"

policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit

pipelines:
    # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
    userPipeline:
        apiEndpoints:
            - user
        policies:
            - proxy:
                  - action:
                        serviceEndpoint: userService
    questionPipeline:
        apiEndpoints:
            - questionBank
        policies:
            - proxy:
                  - action:
                        serviceEndpoint: questionService

routes:
