http:
    port: 8080
https:
    port: 8080
admin:
    port: 9876
    host: localhost
apiEndpoints:
    # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
    user:
        host: "*"
        paths:
            - "/api/users"
            - "/api/login"
            - "/api/logout"
            - "/api/token-login"
    questionBank:
        host: "*"
        paths:
            - "/add-new-question"
            - "/get-all-questions"
            - "/delete-question"
            - "/edit-question"
    compiler:
        host: "*"
        paths:
            - "/compile"
            - "/enqueue-request"

serviceEndpoints:
    # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
    # For deployment, uncomment the environment variables and comment the localhost urls.
    userService:
        url: "http://localhost:3001"
        # url: "${USER_SERVER_URL}"
    questionService:
        url: "http://localhost:3002"
        # url: "${QUESTION_SERVICE_URL}"
    compilerService:
        url: "http://localhost:3006"
        
policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
    - rabbitmq-middleware-policy

pipelines:
    # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
    userPipeline:
        apiEndpoints:
            - user
        policies:
            - log:
                - action:
                    message: ${req.method} ${req.originalUrl} # parameter for log action
            - proxy:
                  - action:
                        serviceEndpoint: userService
                        timeout: 65000
    questionPipeline:
        apiEndpoints:
            - questionBank
        policies:
            - log:
                - action:
                    message: ${req.method} ${req.originalUrl} # parameter for log action
            - proxy:
                  - action:
                        serviceEndpoint: questionService
                        timeout: 65000
    compilerPipeline:
        apiEndpoints:
            - compiler
        policies:
            - rabbitmq-middleware-policy:    

routes:
