POST http://localhost:3001/api/login
Content-Type: application/json

{
    "email": "tobihy@gmail.com",
    "password": "password"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "tobihy",
    "email": "tobihy@gmail.com",
    "password": "password"
}